apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
  - ../../base
  - nfs-pv.yaml
  - nfs-pvc.yaml

replicas:
  - name: hello-nginx
    count: 6

labels:
  - pairs:
      environment: prod

patches:
  - target:
      kind: Deployment
      name: hello-nginx
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: hello-nginx
      spec:
        template:
          spec:
            topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: ScheduleAnyway
              labelSelector:
                matchLabels:
                  app: hello-nginx

