apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../base
  - nfs-pv.yaml
  - nfs-pvc.yaml

replicas:
  - name: hello-nginx
    count: 1

labels:
  - pairs:
      environment: dev

