apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-nginx
spec:
  replicas: 4
  selector:
    matchLabels:
      app: hello-nginx
  template:
    metadata:
      labels:
        app: hello-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:stable-alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: webcontent
              mountPath: /usr/share/nginx/html/web-app
        - name: shell
          image: ubuntu:22.04
          command:
            - tail
            - -f
            - /dev/null
          tty: true
          stdin: true
      volumes:
        - name: webcontent
          persistentVolumeClaim:
            claimName: nfs-pvc
